sonar.projectKey=Verx-Consolidado
sonar.projectName=API Consolidado
sonar.working.directory=C:\\Note_luis\\Projetos\\Teste-Verx\\.sonarqube\\out\\.sonar
sonar.projectBaseDir=C:\\Note_luis\\Projetos\\Teste-Verx
sonar.pullrequest.cache.basepath=C:\\Note_luis\\Projetos\\Teste-Verx
sonar.sources=\
"C:\\Note_luis\\Projetos\\Teste-Verx\\keycloak\\realm-export.json",\
"C:\\Note_luis\\Projetos\\Teste-Verx\\src\\Lancamentos\\Lancamentos.API\\appsettings.Development.json",\
"C:\\Note_luis\\Projetos\\Teste-Verx\\src\\Lancamentos\\Lancamentos.API\\appsettings.json",\
"C:\\Note_luis\\Projetos\\Teste-Verx\\src\\Lancamentos\\Lancamentos.API\\Dockerfile",\
"C:\\Note_luis\\Projetos\\Teste-Verx\\src\\Lancamentos\\Lancamentos.API\\obj\\Lancamentos.API.csproj.nuget.dgspec.json",\
"C:\\Note_luis\\Projetos\\Teste-Verx\\src\\Lancamentos\\Lancamentos.API\\obj\\project.assets.json",\
"C:\\Note_luis\\Projetos\\Teste-Verx\\src\\Lancamentos\\Lancamentos.API\\Properties\\launchSettings.json",\
"C:\\Note_luis\\Projetos\\Teste-Verx\\src\\Lancamentos\\Lancamentos.Application\\obj\\Lancamentos.Application.csproj.nuget.dgspec.json",\
"C:\\Note_luis\\Projetos\\Teste-Verx\\src\\Lancamentos\\Lancamentos.Application\\obj\\project.assets.json",\
"C:\\Note_luis\\Projetos\\Teste-Verx\\src\\Lancamentos\\Lancamentos.Domain\\obj\\Lancamentos.Domain.csproj.nuget.dgspec.json",\
"C:\\Note_luis\\Projetos\\Teste-Verx\\src\\Lancamentos\\Lancamentos.Domain\\obj\\project.assets.json",\
"C:\\Note_luis\\Projetos\\Teste-Verx\\src\\Lancamentos\\Lancamentos.Infrastructure\\obj\\Lancamentos.Infrastructure.csproj.nuget.dgspec.json",\
"C:\\Note_luis\\Projetos\\Teste-Verx\\src\\Lancamentos\\Lancamentos.Infrastructure\\obj\\project.assets.json",\
"C:\\Note_luis\\Projetos\\Teste-Verx\\src\\Lancamentos\\Lancamentos.UnitTests\\obj\\Lancamentos.UnitTests.csproj.nuget.dgspec.json",\
"C:\\Note_luis\\Projetos\\Teste-Verx\\src\\Lancamentos\\Lancamentos.UnitTests\\obj\\project.assets.json",\
"C:\\Note_luis\\Projetos\\Teste-Verx\\src\\Lancamentos\\Lancamentos.UnitTests\\Lancamentos.UnitTests\\obj\\Lancamentos.UnitTests.csproj.nuget.dgspec.json",\
"C:\\Note_luis\\Projetos\\Teste-Verx\\src\\Lancamentos\\Lancamentos.UnitTests\\Lancamentos.UnitTests\\obj\\project.assets.json",\
"C:\\Note_luis\\Projetos\\Teste-Verx\\src\\Lancamentos\\Lancamentos.API\\bin\\Debug\\net10.0\\appsettings.Development.json",\
"C:\\Note_luis\\Projetos\\Teste-Verx\\src\\Lancamentos\\Lancamentos.API\\bin\\Debug\\net10.0\\appsettings.json",\
"C:\\Note_luis\\Projetos\\Teste-Verx\\src\\Lancamentos\\Lancamentos.API\\bin\\Debug\\net10.0\\Lancamentos.API.deps.json",\
"C:\\Note_luis\\Projetos\\Teste-Verx\\src\\Lancamentos\\Lancamentos.API\\bin\\Debug\\net10.0\\Lancamentos.API.runtimeconfig.json",\
"C:\\Note_luis\\Projetos\\Teste-Verx\\src\\Lancamentos\\Lancamentos.API\\bin\\Debug\\net10.0\\Lancamentos.API.staticwebassets.endpoints.json",\
"C:\\Note_luis\\Projetos\\Teste-Verx\\src\\Lancamentos\\Lancamentos.API\\obj\\Debug\\net10.0\\rjsmcshtml.dswa.cache.json",\
"C:\\Note_luis\\Projetos\\Teste-Verx\\src\\Lancamentos\\Lancamentos.API\\obj\\Debug\\net10.0\\rjsmrazor.dswa.cache.json",\
"C:\\Note_luis\\Projetos\\Teste-Verx\\src\\Lancamentos\\Lancamentos.API\\obj\\Debug\\net10.0\\rpswa.dswa.cache.json",\
"C:\\Note_luis\\Projetos\\Teste-Verx\\src\\Lancamentos\\Lancamentos.API\\obj\\Debug\\net10.0\\staticwebassets.build.endpoints.json",\
"C:\\Note_luis\\Projetos\\Teste-Verx\\src\\Lancamentos\\Lancamentos.API\\obj\\Debug\\net10.0\\staticwebassets.build.json",\
"C:\\Note_luis\\Projetos\\Teste-Verx\\src\\Lancamentos\\Lancamentos.Application\\bin\\Debug\\net10.0\\Lancamentos.Application.deps.json",\
"C:\\Note_luis\\Projetos\\Teste-Verx\\src\\Lancamentos\\Lancamentos.Domain\\bin\\Debug\\net10.0\\Lancamentos.Domain.deps.json",\
"C:\\Note_luis\\Projetos\\Teste-Verx\\src\\Lancamentos\\Lancamentos.Infrastructure\\bin\\Debug\\net10.0\\Lancamentos.Infrastructure.deps.json",\
"C:\\Note_luis\\Projetos\\Teste-Verx\\src\\Lancamentos\\Lancamentos.UnitTests\\bin\\Debug\\net10.0\\appsettings.Development.json",\
"C:\\Note_luis\\Projetos\\Teste-Verx\\src\\Lancamentos\\Lancamentos.UnitTests\\bin\\Debug\\net10.0\\appsettings.json",\
"C:\\Note_luis\\Projetos\\Teste-Verx\\src\\Lancamentos\\Lancamentos.UnitTests\\bin\\Debug\\net10.0\\Lancamentos.API.deps.json",\
"C:\\Note_luis\\Projetos\\Teste-Verx\\src\\Lancamentos\\Lancamentos.UnitTests\\bin\\Debug\\net10.0\\Lancamentos.API.runtimeconfig.json",\
"C:\\Note_luis\\Projetos\\Teste-Verx\\src\\Lancamentos\\Lancamentos.UnitTests\\bin\\Debug\\net10.0\\Lancamentos.API.staticwebassets.endpoints.json",\
"C:\\Note_luis\\Projetos\\Teste-Verx\\src\\Lancamentos\\Lancamentos.UnitTests\\bin\\Debug\\net10.0\\Lancamentos.UnitTests.deps.json",\
"C:\\Note_luis\\Projetos\\Teste-Verx\\src\\Lancamentos\\Lancamentos.UnitTests\\bin\\Debug\\net10.0\\Lancamentos.UnitTests.runtimeconfig.json",\
"C:\\Note_luis\\Projetos\\Teste-Verx\\docker-compose.yml",\
"C:\\Note_luis\\Projetos\\Teste-Verx\\prometheus.yml"

B6D2597F-CA19-41A8-A9DF-4F7CDA2FCB9B.sonar.projectKey=Verx-Consolidado:B6D2597F-CA19-41A8-A9DF-4F7CDA2FCB9B
B6D2597F-CA19-41A8-A9DF-4F7CDA2FCB9B.sonar.projectName=Consolidado.Domain
B6D2597F-CA19-41A8-A9DF-4F7CDA2FCB9B.sonar.projectBaseDir=C:\\Note_luis\\Projetos\\Teste-Verx\\src\\Consolidado\\Consolidado.Domain
B6D2597F-CA19-41A8-A9DF-4F7CDA2FCB9B.sonar.sourceEncoding=utf-8
B6D2597F-CA19-41A8-A9DF-4F7CDA2FCB9B.sonar.tests=
B6D2597F-CA19-41A8-A9DF-4F7CDA2FCB9B.sonar.sources=\
"C:\\Note_luis\\Projetos\\Teste-Verx\\src\\Consolidado\\Consolidado.Domain\\Entities\\SaldoDiario.cs",\
"C:\\Note_luis\\Projetos\\Teste-Verx\\src\\Consolidado\\Consolidado.Domain\\Repositories\\ISaldoRepository.cs",\
"C:\\Note_luis\\Projetos\\Teste-Verx\\src\\Consolidado\\Consolidado.Domain\\obj\\Consolidado.Domain.csproj.nuget.dgspec.json",\
"C:\\Note_luis\\Projetos\\Teste-Verx\\src\\Consolidado\\Consolidado.Domain\\obj\\project.assets.json",\
"C:\\Note_luis\\Projetos\\Teste-Verx\\src\\Consolidado\\Consolidado.Domain\\bin\\Debug\\net10.0\\Consolidado.Domain.deps.json"

B6D2597F-CA19-41A8-A9DF-4F7CDA2FCB9B.sonar.cs.analyzer.projectOutPaths=\
"C:\\Note_luis\\Projetos\\Teste-Verx\\.sonarqube\\out\\0"
B6D2597F-CA19-41A8-A9DF-4F7CDA2FCB9B.sonar.cs.roslyn.reportFilePaths=\
"C:\\Note_luis\\Projetos\\Teste-Verx\\.sonarqube\\out\\0\\Issues.json"
B6D2597F-CA19-41A8-A9DF-4F7CDA2FCB9B.sonar.cs.scanner.telemetry=\
"C:\\Note_luis\\Projetos\\Teste-Verx\\.sonarqube\\out\\0\\Telemetry.json"

B6D2597F-CA19-41A8-A9DF-4F7CDA2FCB9B.sonar.working.directory=C:\\Note_luis\\Projetos\\Teste-Verx\\.sonarqube\\out\\.sonar\\mod0
D60DF1F2-449C-4E09-BE0D-456E28938F87.sonar.projectKey=Verx-Consolidado:D60DF1F2-449C-4E09-BE0D-456E28938F87
D60DF1F2-449C-4E09-BE0D-456E28938F87.sonar.projectName=Shared.Contracts
D60DF1F2-449C-4E09-BE0D-456E28938F87.sonar.projectBaseDir=C:\\Note_luis\\Projetos\\Teste-Verx\\src\\Shared.Contracts
D60DF1F2-449C-4E09-BE0D-456E28938F87.sonar.sourceEncoding=utf-8
D60DF1F2-449C-4E09-BE0D-456E28938F87.sonar.tests=
D60DF1F2-449C-4E09-BE0D-456E28938F87.sonar.sources=\
"C:\\Note_luis\\Projetos\\Teste-Verx\\src\\Shared.Contracts\\obj\\project.assets.json",\
"C:\\Note_luis\\Projetos\\Teste-Verx\\src\\Shared.Contracts\\obj\\Shared.Contracts.csproj.nuget.dgspec.json",\
"C:\\Note_luis\\Projetos\\Teste-Verx\\src\\Shared.Contracts\\bin\\Debug\\net10.0\\Shared.Contracts.deps.json",\
"C:\\Note_luis\\Projetos\\Teste-Verx\\src\\Shared.Contracts\\LancamentoCriadoEvent.cs"

D60DF1F2-449C-4E09-BE0D-456E28938F87.sonar.cs.analyzer.projectOutPaths=\
"C:\\Note_luis\\Projetos\\Teste-Verx\\.sonarqube\\out\\1"
D60DF1F2-449C-4E09-BE0D-456E28938F87.sonar.cs.roslyn.reportFilePaths=\
"C:\\Note_luis\\Projetos\\Teste-Verx\\.sonarqube\\out\\1\\Issues.json"
D60DF1F2-449C-4E09-BE0D-456E28938F87.sonar.cs.scanner.telemetry=\
"C:\\Note_luis\\Projetos\\Teste-Verx\\.sonarqube\\out\\1\\Telemetry.json"

D60DF1F2-449C-4E09-BE0D-456E28938F87.sonar.working.directory=C:\\Note_luis\\Projetos\\Teste-Verx\\.sonarqube\\out\\.sonar\\mod1
B14F2368-1F81-467A-93A1-D55E495FD1CE.sonar.projectKey=Verx-Consolidado:B14F2368-1F81-467A-93A1-D55E495FD1CE
B14F2368-1F81-467A-93A1-D55E495FD1CE.sonar.projectName=Consolidado.Infrastructure
B14F2368-1F81-467A-93A1-D55E495FD1CE.sonar.projectBaseDir=C:\\Note_luis\\Projetos\\Teste-Verx\\src\\Consolidado\\Consolidado.Infrastructure
B14F2368-1F81-467A-93A1-D55E495FD1CE.sonar.sourceEncoding=utf-8
B14F2368-1F81-467A-93A1-D55E495FD1CE.sonar.tests=
B14F2368-1F81-467A-93A1-D55E495FD1CE.sonar.sources=\
"C:\\Note_luis\\Projetos\\Teste-Verx\\src\\Consolidado\\Consolidado.Infrastructure\\obj\\Consolidado.Infrastructure.csproj.nuget.dgspec.json",\
"C:\\Note_luis\\Projetos\\Teste-Verx\\src\\Consolidado\\Consolidado.Infrastructure\\obj\\project.assets.json",\
"C:\\Note_luis\\Projetos\\Teste-Verx\\src\\Consolidado\\Consolidado.Infrastructure\\bin\\Debug\\net10.0\\Consolidado.Infrastructure.deps.json",\
"C:\\Note_luis\\Projetos\\Teste-Verx\\src\\Consolidado\\Consolidado.Infrastructure\\Data\\ConsolidadoDbContext.cs",\
"C:\\Note_luis\\Projetos\\Teste-Verx\\src\\Consolidado\\Consolidado.Infrastructure\\Repositories\\SaldoRepository.cs"

B14F2368-1F81-467A-93A1-D55E495FD1CE.sonar.cs.analyzer.projectOutPaths=\
"C:\\Note_luis\\Projetos\\Teste-Verx\\.sonarqube\\out\\2"
B14F2368-1F81-467A-93A1-D55E495FD1CE.sonar.cs.roslyn.reportFilePaths=\
"C:\\Note_luis\\Projetos\\Teste-Verx\\.sonarqube\\out\\2\\Issues.json"
B14F2368-1F81-467A-93A1-D55E495FD1CE.sonar.cs.scanner.telemetry=\
"C:\\Note_luis\\Projetos\\Teste-Verx\\.sonarqube\\out\\2\\Telemetry.json"

B14F2368-1F81-467A-93A1-D55E495FD1CE.sonar.working.directory=C:\\Note_luis\\Projetos\\Teste-Verx\\.sonarqube\\out\\.sonar\\mod2
D0E064CF-385F-48C9-AD78-3750D9D2413B.sonar.projectKey=Verx-Consolidado:D0E064CF-385F-48C9-AD78-3750D9D2413B
D0E064CF-385F-48C9-AD78-3750D9D2413B.sonar.projectName=Consolidado.Application
D0E064CF-385F-48C9-AD78-3750D9D2413B.sonar.projectBaseDir=C:\\Note_luis\\Projetos\\Teste-Verx\\src\\Consolidado\\Consolidado.Application
D0E064CF-385F-48C9-AD78-3750D9D2413B.sonar.sourceEncoding=utf-8
D0E064CF-385F-48C9-AD78-3750D9D2413B.sonar.tests=
D0E064CF-385F-48C9-AD78-3750D9D2413B.sonar.sources=\
"C:\\Note_luis\\Projetos\\Teste-Verx\\src\\Consolidado\\Consolidado.Application\\obj\\Consolidado.Application.csproj.nuget.dgspec.json",\
"C:\\Note_luis\\Projetos\\Teste-Verx\\src\\Consolidado\\Consolidado.Application\\obj\\project.assets.json",\
"C:\\Note_luis\\Projetos\\Teste-Verx\\src\\Consolidado\\Consolidado.Application\\bin\\Debug\\net10.0\\Consolidado.Application.deps.json",\
"C:\\Note_luis\\Projetos\\Teste-Verx\\src\\Consolidado\\Consolidado.Application\\Consumers\\LancamentoCriadoConsumer.cs",\
"C:\\Note_luis\\Projetos\\Teste-Verx\\src\\Consolidado\\Consolidado.Application\\Services\\SaldoService.cs"

D0E064CF-385F-48C9-AD78-3750D9D2413B.sonar.cs.analyzer.projectOutPaths=\
"C:\\Note_luis\\Projetos\\Teste-Verx\\.sonarqube\\out\\3"
D0E064CF-385F-48C9-AD78-3750D9D2413B.sonar.cs.roslyn.reportFilePaths=\
"C:\\Note_luis\\Projetos\\Teste-Verx\\.sonarqube\\out\\3\\Issues.json"
D0E064CF-385F-48C9-AD78-3750D9D2413B.sonar.cs.scanner.telemetry=\
"C:\\Note_luis\\Projetos\\Teste-Verx\\.sonarqube\\out\\3\\Telemetry.json"

D0E064CF-385F-48C9-AD78-3750D9D2413B.sonar.working.directory=C:\\Note_luis\\Projetos\\Teste-Verx\\.sonarqube\\out\\.sonar\\mod3
04EB6D7B-0613-432F-90A9-51C88D85F0C6.sonar.projectKey=Verx-Consolidado:04EB6D7B-0613-432F-90A9-51C88D85F0C6
04EB6D7B-0613-432F-90A9-51C88D85F0C6.sonar.projectName=Consolidado.API
04EB6D7B-0613-432F-90A9-51C88D85F0C6.sonar.projectBaseDir=C:\\Note_luis\\Projetos\\Teste-Verx\\src\\Consolidado\\Consolidado.API
04EB6D7B-0613-432F-90A9-51C88D85F0C6.sonar.sourceEncoding=utf-8
04EB6D7B-0613-432F-90A9-51C88D85F0C6.sonar.tests=
04EB6D7B-0613-432F-90A9-51C88D85F0C6.sonar.sources=\
"C:\\Note_luis\\Projetos\\Teste-Verx\\src\\Consolidado\\Consolidado.API\\appsettings.Development.json",\
"C:\\Note_luis\\Projetos\\Teste-Verx\\src\\Consolidado\\Consolidado.API\\appsettings.json",\
"C:\\Note_luis\\Projetos\\Teste-Verx\\src\\Consolidado\\Consolidado.API\\Dockerfile",\
"C:\\Note_luis\\Projetos\\Teste-Verx\\src\\Consolidado\\Consolidado.API\\obj\\Consolidado.API.csproj.nuget.dgspec.json",\
"C:\\Note_luis\\Projetos\\Teste-Verx\\src\\Consolidado\\Consolidado.API\\obj\\project.assets.json",\
"C:\\Note_luis\\Projetos\\Teste-Verx\\src\\Consolidado\\Consolidado.API\\Properties\\launchSettings.json",\
"C:\\Note_luis\\Projetos\\Teste-Verx\\src\\Consolidado\\Consolidado.API\\bin\\Debug\\net10.0\\appsettings.Development.json",\
"C:\\Note_luis\\Projetos\\Teste-Verx\\src\\Consolidado\\Consolidado.API\\bin\\Debug\\net10.0\\appsettings.json",\
"C:\\Note_luis\\Projetos\\Teste-Verx\\src\\Consolidado\\Consolidado.API\\bin\\Debug\\net10.0\\Consolidado.API.deps.json",\
"C:\\Note_luis\\Projetos\\Teste-Verx\\src\\Consolidado\\Consolidado.API\\bin\\Debug\\net10.0\\Consolidado.API.runtimeconfig.json",\
"C:\\Note_luis\\Projetos\\Teste-Verx\\src\\Consolidado\\Consolidado.API\\bin\\Debug\\net10.0\\Consolidado.API.staticwebassets.endpoints.json",\
"C:\\Note_luis\\Projetos\\Teste-Verx\\src\\Consolidado\\Consolidado.API\\obj\\Debug\\net10.0\\rjsmcshtml.dswa.cache.json",\
"C:\\Note_luis\\Projetos\\Teste-Verx\\src\\Consolidado\\Consolidado.API\\obj\\Debug\\net10.0\\rjsmrazor.dswa.cache.json",\
"C:\\Note_luis\\Projetos\\Teste-Verx\\src\\Consolidado\\Consolidado.API\\obj\\Debug\\net10.0\\rpswa.dswa.cache.json",\
"C:\\Note_luis\\Projetos\\Teste-Verx\\src\\Consolidado\\Consolidado.API\\obj\\Debug\\net10.0\\staticwebassets.build.endpoints.json",\
"C:\\Note_luis\\Projetos\\Teste-Verx\\src\\Consolidado\\Consolidado.API\\obj\\Debug\\net10.0\\staticwebassets.build.json",\
"C:\\Note_luis\\Projetos\\Teste-Verx\\src\\Consolidado\\Consolidado.API\\Consumers\\LancamentoCriadoConsumer.cs",\
"C:\\Note_luis\\Projetos\\Teste-Verx\\src\\Consolidado\\Consolidado.API\\Controllers\\AuthController.cs",\
"C:\\Note_luis\\Projetos\\Teste-Verx\\src\\Consolidado\\Consolidado.API\\Controllers\\ConsolidadoController.cs",\
"C:\\Note_luis\\Projetos\\Teste-Verx\\src\\Consolidado\\Consolidado.API\\Data\\ConsolidadoDbContext.cs",\
"C:\\Note_luis\\Projetos\\Teste-Verx\\src\\Consolidado\\Consolidado.API\\Domain\\SaldoDiario.cs",\
"C:\\Note_luis\\Projetos\\Teste-Verx\\src\\Consolidado\\Consolidado.API\\Program.cs",\
"C:\\Note_luis\\Projetos\\Teste-Verx\\src\\Consolidado\\Consolidado.API\\obj\\Debug\\net10.0\\Consolidado.API.GlobalUsings.g.cs",\
"C:\\Note_luis\\Projetos\\Teste-Verx\\src\\Consolidado\\Consolidado.API\\obj\\Debug\\net10.0\\.NETCoreApp,Version=v10.0.AssemblyAttributes.cs",\
"C:\\Note_luis\\Projetos\\Teste-Verx\\src\\Consolidado\\Consolidado.API\\obj\\Debug\\net10.0\\Consolidado.API.AssemblyInfo.cs",\
"C:\\Note_luis\\Projetos\\Teste-Verx\\src\\Consolidado\\Consolidado.API\\obj\\Debug\\net10.0\\Consolidado.API.MvcApplicationPartsAssemblyInfo.cs",\
"C:\\Note_luis\\Projetos\\Teste-Verx\\src\\Consolidado\\Consolidado.API\\Consolidado.API.http"

04EB6D7B-0613-432F-90A9-51C88D85F0C6.sonar.cs.analyzer.projectOutPaths=\
"C:\\Note_luis\\Projetos\\Teste-Verx\\.sonarqube\\out\\4"
04EB6D7B-0613-432F-90A9-51C88D85F0C6.sonar.cs.roslyn.reportFilePaths=\
"C:\\Note_luis\\Projetos\\Teste-Verx\\.sonarqube\\out\\4\\Issues.json"
04EB6D7B-0613-432F-90A9-51C88D85F0C6.sonar.cs.scanner.telemetry=\
"C:\\Note_luis\\Projetos\\Teste-Verx\\.sonarqube\\out\\4\\Telemetry.json"

04EB6D7B-0613-432F-90A9-51C88D85F0C6.sonar.working.directory=C:\\Note_luis\\Projetos\\Teste-Verx\\.sonarqube\\out\\.sonar\\mod4
DB0D366C-7051-47A6-BBBD-762257D3298E.sonar.projectKey=Verx-Consolidado:DB0D366C-7051-47A6-BBBD-762257D3298E
DB0D366C-7051-47A6-BBBD-762257D3298E.sonar.projectName=Consolidado.UnitTests
DB0D366C-7051-47A6-BBBD-762257D3298E.sonar.projectBaseDir=C:\\Note_luis\\Projetos\\Teste-Verx\\src\\Consolidado\\Consolidado.UnitTests
DB0D366C-7051-47A6-BBBD-762257D3298E.sonar.sourceEncoding=utf-8
DB0D366C-7051-47A6-BBBD-762257D3298E.sonar.sources=
DB0D366C-7051-47A6-BBBD-762257D3298E.sonar.tests=\
"C:\\Note_luis\\Projetos\\Teste-Verx\\src\\Consolidado\\Consolidado.UnitTests\\obj\\Consolidado.UnitTests.csproj.nuget.dgspec.json",\
"C:\\Note_luis\\Projetos\\Teste-Verx\\src\\Consolidado\\Consolidado.UnitTests\\obj\\project.assets.json",\
"C:\\Note_luis\\Projetos\\Teste-Verx\\src\\Consolidado\\Consolidado.UnitTests\\bin\\Debug\\net10.0\\appsettings.Development.json",\
"C:\\Note_luis\\Projetos\\Teste-Verx\\src\\Consolidado\\Consolidado.UnitTests\\bin\\Debug\\net10.0\\appsettings.json",\
"C:\\Note_luis\\Projetos\\Teste-Verx\\src\\Consolidado\\Consolidado.UnitTests\\bin\\Debug\\net10.0\\Consolidado.API.deps.json",\
"C:\\Note_luis\\Projetos\\Teste-Verx\\src\\Consolidado\\Consolidado.UnitTests\\bin\\Debug\\net10.0\\Consolidado.API.runtimeconfig.json",\
"C:\\Note_luis\\Projetos\\Teste-Verx\\src\\Consolidado\\Consolidado.UnitTests\\bin\\Debug\\net10.0\\Consolidado.API.staticwebassets.endpoints.json",\
"C:\\Note_luis\\Projetos\\Teste-Verx\\src\\Consolidado\\Consolidado.UnitTests\\bin\\Debug\\net10.0\\Consolidado.UnitTests.deps.json",\
"C:\\Note_luis\\Projetos\\Teste-Verx\\src\\Consolidado\\Consolidado.UnitTests\\bin\\Debug\\net10.0\\Consolidado.UnitTests.runtimeconfig.json",\
"C:\\Note_luis\\Projetos\\Teste-Verx\\src\\Consolidado\\Consolidado.UnitTests\\Consumers\\LancamentoCriadoConsumerTests.cs",\
"C:\\Note_luis\\Projetos\\Teste-Verx\\src\\Consolidado\\Consolidado.UnitTests\\Controllers\\ConsolidadoControllerTests.cs",\
"C:\\Note_luis\\Projetos\\Teste-Verx\\src\\Consolidado\\Consolidado.UnitTests\\Domain\\SaldoDiarioTests.cs",\
"C:\\Note_luis\\Projetos\\Teste-Verx\\src\\Consolidado\\Consolidado.UnitTests\\Infrastructure\\SaldoRepositoryTests.cs",\
"C:\\Note_luis\\Projetos\\Teste-Verx\\src\\Consolidado\\Consolidado.UnitTests\\Integration\\ConsolidadoIntegrationTests.cs",\
"C:\\Note_luis\\Projetos\\Teste-Verx\\src\\Consolidado\\Consolidado.UnitTests\\Services\\SaldoServiceTests.cs",\
"C:\\Note_luis\\Projetos\\Teste-Verx\\src\\Consolidado\\Consolidado.UnitTests\\coverage.opencover.xml"

DB0D366C-7051-47A6-BBBD-762257D3298E.sonar.cs.analyzer.projectOutPaths=\
"C:\\Note_luis\\Projetos\\Teste-Verx\\.sonarqube\\out\\5"
DB0D366C-7051-47A6-BBBD-762257D3298E.sonar.cs.roslyn.reportFilePaths=\
"C:\\Note_luis\\Projetos\\Teste-Verx\\.sonarqube\\out\\5\\Issues.json"
DB0D366C-7051-47A6-BBBD-762257D3298E.sonar.cs.scanner.telemetry=\
"C:\\Note_luis\\Projetos\\Teste-Verx\\.sonarqube\\out\\5\\Telemetry.json"

DB0D366C-7051-47A6-BBBD-762257D3298E.sonar.working.directory=C:\\Note_luis\\Projetos\\Teste-Verx\\.sonarqube\\out\\.sonar\\mod5
sonar.host.url=http://localhost:9000
sonar.cs.opencover.reportsPaths=src/Consolidado/Consolidado.UnitTests/coverage.opencover.xml
sonar.coverage.exclusions=**/Program.cs,**/Properties/**,**/Data/**
sonar.exclusions=src/Consolidado/Consolidado.UnitTests/coverage.opencover.xml
sonar.visualstudio.enable=false

sonar.modules=B6D2597F-CA19-41A8-A9DF-4F7CDA2FCB9B,D60DF1F2-449C-4E09-BE0D-456E28938F87,B14F2368-1F81-467A-93A1-D55E495FD1CE,D0E064CF-385F-48C9-AD78-3750D9D2413B,04EB6D7B-0613-432F-90A9-51C88D85F0C6,DB0D366C-7051-47A6-BBBD-762257D3298E

